changelog:
  categories:
    - title: Enhancements
      labels:
        - type:enhancement
    - title: Bug Fixes
      labels:
        - type:bug
    - title: Other Changes
      labels:
        - "*"
