name: cd

on:
  workflow_run:
    workflows: ["ci"]
    branches-ignore: ["*"]
    types:
      - completed
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - run: pnpm install
    - name: Create GitHub release
      run: |
        pnpm run vscode:package
        gh release create "$GITHUB_REF_NAME" --title "$GITHUB_REF_NAME" --generate-notes slidaiv-*.vsix
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish CLI to npm
      run: |
        pnpm run cli:compile
        pnpm publish --no-git-checks --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_CONFIG_PROVENANCE: true
    - name: Publish VSCode extension to Marketplace
      run: pnpm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
