name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
    - run: sudo apt-get install -y xvfb
    - run: pnpm install
    - run: xvfb-run --auto-servernum pnpm test
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: |
        pnpm run vscode:package
        gh release create "$GITHUB_REF_NAME" --title "$GITHUB_REF_NAME" --notes "Release $GITHUB_REF_NAME" slidaiv-*.vsix

